services:
  - type: web
    name: macro-dashboard
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium chromium-driver && \
      pip install -r requirements.txt
    startCommand: "bash start.sh"
